# Generated by Django 4.2.7 on 2023-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TASK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.TextField(max_length=1000, null=True)),
                ('email', models.TextField(max_length=100, null=True)),
                ('Mobile', models.TextField(max_length=1000, null=True)),
                ('Degree_Department', models.IntegerField(null=True)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('Skillset', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('discount_percent', models.IntegerField(null=True)),
                ('discounted_price', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
